### ISSUE TITLE
Placement of interactive dashboard in JupyterLab

### ISSUE THREAD

**Issue by zzhengnan** [dask/dask-examples#178]
Not sure if this strictly counts as a bug, but here goes.

When running the [example notebook for `delayed`](https://github.com/dask/dask-examples/blob/master/delayed.ipynb) online (after clicking "launch binder"), I was expecting the interactive dashboard to show up in the two panes on the right side of the JupyterLab window. This turned out not to be the case, as the two panes remained blank throughout.

To get the dashboard to appear, I had to click the link that shows up after a `Client` object is instantiated. 

Is this intended behavior? Is there a way to peg the dashboard to the two "pre-allocated" panes _within_ the same JupyterLab window?

<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/17503044/100163699-43069e00-2e84-11eb-9fe1-a74402dd181c.png)

![image](https://user-images.githubusercontent.com/17503044/100163942-ccb66b80-2e84-11eb-8caf-19091b86578d.png)

</details>

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @zzhengnan! The dashboard should show up and connect to your `Client` automatically. However the "task stream" and "progress" plots don't show any content until a computation starts on the cluster. Looking at the delayed notebook, the seventh code cell is where the first computation on the cluster occurs (`z.compute()` in the "Run in parallel" section). What happens when you run that cell? Do things show up in the plots?

**Comment by zzhengnan** [comment]
Thanks for the context, @jrbourbeau. I just tested and can confirm the dashboard shows up as expected when `.compute()` is called for the first time. I was being too impatient :)
