### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-examples#2]
This repository could use continuous integration to ensure that the examples continue to work over time

I'm not familiar with tools to test notebooks, but other projects do this, so it must be doable.

**Comment by mholtzscher** [comment]
@mrocklin do you have any example projects that do the testing you're looking for? I'd be interested in taking on this issue

**Comment by mrocklin** [comment]
Good question.  I suspect that Scikit-Learn does this with [their example gallery](http://scikit-learn.org/stable/auto_examples/index.html).  I suspect that @TomAugspurger might know more as well.

**Comment by mrocklin** [comment]
> I'd be interested in taking on this issue

This would be great!

**Comment by TomAugspurger** [comment]
Scikit-Learn uses sphinx-gallery to to convert an `.py` file to
restructured text & jupyter notebooks. I presume they're just running the
python file.

Since we're starting with notebooks, I think the best thing to do is to run
`jupyter nbconvert` on each notebook, to "convert" each to a notebook,
while executing it.

https://nbconvert.readthedocs.io/en/latest/execute_api.html

The main thing is to set a higher timeout I think.

I think the main thing we care about is whether or not the notebook runs.
We don't care about the exact output at all. If the notebook has an
exception, then we want the script executing the notebook to fail, so that
the CI fails.
